name = "Genser"
uuid = "fd006b10-c86c-4a41-b27e-30173f8e085d"
authors = ["Mark Wardle <mwwardle@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[compat]
Requires = "1.1"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
